### ISSUE TITLE
Buggy brand input field

### ISSUE THREAD

**Issue by uncenter** [mondeja/simple-icons-website-rs#221]
For some reason the [brand input component](https://github.com/mondeja/simple-icons-website-rs/blob/master/components/src/preview_generator/inputs.rs#L305-L373) isn't working as expected. Sometimes I simply cannot type certain letters! In the gif below, I am typing "A", then "B", and then "C"... but the "C" doesn't work.

![Screenshot 2024-03-13 at 11 38 30 (Arc)](https://github.com/mondeja/simple-icons-website-rs/assets/47499684/f3a678d3-7067-4f41-8792-ccc5817fcc70)

**Comment by mondeja** [comment]
Wow, good catch! This is because there are [Keyboard shortcuts](https://github.com/mondeja/simple-icons-website-rs/blob/master/USAGE.md#keyboard-shortcuts) configured and [leptos-hotkeys](https://github.com/gaucho-labs/leptos-hotkeys) seems to be confused about <kbd>Ctrl</kbd> and <kbd>Shift</kbd>. Note that the same happens for <kbd>Shift</kbd> + <kbd>S</kbd>.

**Comment by uncenter** [comment]
Huh but just FYI lowercase `c` also doesn't work? In that case I'm not holding down either `Ctrl` or `Shift`...

**Comment by mondeja** [comment]
That's true, something really bad seems to be hapenning with leptos-hotkeys... I'll investigate it after the release of v0.2.0.
